### ISSUE TITLE
Problem with "tab center"

### ISSUE THREAD

**Issue by ledemon** [tumpio/toolbarpositionchanger#10]
Switching from side tabs to top/bottom tabs block the window tabs and hide the tab bar until restart firefox.

**Comment by tumpio** [comment]
Can you tell me your version of Firefox and your OS?

What do you mean by "window" tabs?

**Comment by ledemon** [comment]
firefox 51.0.1x64, "windows 10" version 1607
Firefox window, all the interface, the tabs are there but without the tab bar and cant change between each other.

**Comment by tumpio** [comment]
I think I got the error. Do you have the location bar moved to bottom?

**Comment by ledemon** [comment]
Originally with your "toolbar position changer" I have the tab bar in bottom but upper the addres bar, with the "tab center" the tab bat move vertically to the left side, but when I choose the option from the "tab center" switch to original position (in my case in bottom window) the tab bar dissapears and block completely  firefox interface but dont freeze or crash and restart keeps the tabs save.

**Comment by tumpio** [comment]
Ok, thanks. This will require patching Tab Center to support TPC. I'll try to make those and let's see if they are accepted.

**Comment by tumpio** [comment]
Patches send. Now they have to be accepted and published in a new release of Tab Center.

**Comment by ledemon** [comment]
Thanks.
This is a little strange, too many addons for doing multiple things, but is great have the options to make the changes one would like and the tab center looks very nice, specially now we have widescreens and a lot of window space without use.
