### ISSUE TITLE
Tab Bar shows in Fullscreen Youtube (HTML5)

### ISSUE THREAD

**Issue by mugenexe** [tumpio/toolbarpositionchanger#4]
Tab bar moved to the bottom results with this, but does not occur when moved back to the default top. 
Let me know if this is reproducible, or if it is only on my end.
Thanks!

**Comment by tumpio** [comment]
Hello!

It doesn't show on my end. Can you provide more information of what could cause it?

What's your Operating system? Do you have other add-ons or themes that could conflict with it?

**Comment by mugenexe** [comment]
Reinstalled the addon and it fixed! 

It was my mistake when adjusting a few things in toolbarpositionchanger.css a while ago. I apologize, it was just me breaking a few things.
Looking closer, I found what I needed. Particularly wanted to remove the padding by adjusting these two:
`#TabsToolbar:not([invertedTabBackground]) {
        padding-top: 0px!important;
    }`
`#browser-bottombox::before {
        height: 0px;
    }`

So all is good. Thanks for such an addon!

**Comment by tumpio** [comment]
Great that it worked out! I think I will adjust those too :+1:

**Comment by tumpio** [comment]
In the next version you shouldn't need to add those modifications any longer.
