### ISSUE TITLE
Themeing bug (Arc Theme)

### ISSUE THREAD

**Issue by siemhermans** [tumpio/toolbarpositionchanger#7]
Hi, when using the Arc (Dark) Theme for Firefox (https://github.com/horst3180/arc-firefox-theme), the background of the main bar is not colored correctly. All other elements are drawn correctly. Your previous plugin Bottom UI did not have problems with this. Currently running Firefox 47 on Ubuntu 16.04. Screenshots are attached below. 

![2016-08-04-1470319165_1919x1056](https://cloud.githubusercontent.com/assets/6272934/17404563/727e8734-5a5c-11e6-9c9b-1b717ebbfacb.png)

**Comment by tumpio** [comment]
Hello, this is fixed in the next version of the add-on. It is currently in the review process which should take only 1-2 days.
