### ISSUE TITLE
49.0 breaks it?

### ISSUE THREAD

**Issue by semicodin** [tumpio/toolbarpositionchanger#8]
**Solved.** You might want to update your Addons listing.  Firefox 49.0 is very squirrelly (touchy) but the way I got this to work was to open the Omnibox and drag items into the Bookmarks Bar **first**.  Once they are there they can be lifted onto the position you want them in.  You can also get rid of the search bar by dragging into Omnibox.

---

Trying to get rid of the search bar and drag some stuff up to the menu bar. I got this working previously but I'm on a new build with FF 49 and either can't remember how to do it -or- n/a because TPC is incompatible.  Thanks.  Excellent addon.

**Comment by tumpio** [comment]
So what actually was not working? Can you be a bit more specific, please? :)

**Comment by tumpio** [comment]
I'll close this. If you still have any problems just open a new issue.
