### ISSUE TITLE
Doesn't works on Firefox developer edition 

### ISSUE THREAD

**Issue by aemonge** [tumpio/toolbarpositionchanger#9]
version 51.0a2
update channelaurora

Can't move my tabs to the bottom.

**Comment by tumpio** [comment]
Hello, it is fixed in v0.2.9
https://github.com/tumpio/toolbarpositionchanger/releases/tag/v0.2.9
https://addons.mozilla.org/addon/toolbar-position-changer/versions/?page=1#version-0.2.9

Can you confirm that everything works.

**Comment by aemonge** [comment]
Yeah !!!!!

It's working, and you've made me SO happy !!!

Thanks !

**Comment by maverick74** [comment]
@tumpio 
Hi!

I didn't want to create a new bug report just to make a question:

Is there a chance for this to work on FF57?

Thanks

**Comment by tumpio** [comment]
@maverick74  Mozilla will end support for classic browser add-ons in Firefox 57. The new add-on model WebExtensions does not support browser interface modifications. This means that Toolbar Position Changer cannot be converted.

I have taken part of the bug that was opened in Bugzilla to add a WebExtension API for browser toolbars. Even if this API would be added, I'm afraid it would be very limited only allowing simple toolbar creation.

https://bugzilla.mozilla.org/show_bug.cgi?id=1215064#c12

P.S. A new issue is always better than reusing old issues. What you can do is to reference the old issue in the new issue report if it is related to your issue. This is not.

**Comment by maverick74** [comment]
Ok. I was guessing this already...

It's very sad to see it go away :(

thanks, @tumpio, for your reply, sympathy and work :)
